version: '3.8'
services:
  delivery-much:
    container_name: delivery-much-container
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 3000:3000
    volumes:
      - .:/code
